### ISSUE TITLE
Includes `implementation` dependency as well as `compile` dependency

### ISSUE THREAD

**Issue by imasahiro** [line/gradle-scripts#44]
Gradle starts to support new type of dependency definition, `implementation` and `api`. And because this gradle-scripts only collects dependencies defined with `compile`, a user cannot publish a correct pom to repository (it generates pom file without any dependency).
We need to support `implementation` for better usability.

**Comment by trustin** [comment]
Sounds like a good idea. Never tried the new configuration model yet, though..

**Comment by mauhiz** [comment]
@ikhoon @minwoox would you be interested in taking this over? Most recent projects don't use old Gradle scopes so this issue has become somewhat important

**Comment by minwoox** [comment]
Ah, I missed that this issue.
I thought there's no problem using `implementation` and `api` because we are already using them.
https://github.com/line/armeria/blob/master/build.gradle#L98-L127
Is there any problem with the newest commit of this script? 🤔

**Comment by minwoox** [comment]
https://github.com/line/gradle-scripts/pull/70/files
This might solve this issue?

**Comment by m50d** [comment]
Latest version does seem to work correctly. Thanks!

**Comment by minwoox** [comment]
Closed by #70
